# Shuttle v1.0.0
# Example configuration document

# Server configuration
[server]
name = "Shuttle Server"
maintainer = "John Smith <john@example.com>"

# Database configuration
[database]
type = "mongo"              # TO BE IMPLEMENTED
address = "127.0.0.1"
port = 27017

[database.authentication]
enabled = false
username = "john"
password = "johnrocks"

# API specifications
[api]

# force-api-spec
# Selects which API specification clients are required to use.
# If set to false or an empty string, clients can use old API versions.
force-api-spec = false

# Uncomment to force usage of API v1
#force-api-spec = "v1"
