# Shuttle v1.1.0
# Example configuration document

# Server configuration
[server]
name = "Shuttle Server"

# Database configuration
[database]
port = 27017
address = "127.0.0.1"

[database.authentication]
username = "username"
password = "password"
authSource = "admin"
authMechanism = "SCRAM-SHA-256"
